# Generated by Django 2.2.26 on 2022-01-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('to_check', 'Oczekuje na sprawdzenie'), ('confirmed', 'Zaakceptowane'), ('rejected', 'Odrzucono')], default='to_check'),
        ),
    ]
