# Generated by Django 2.2.26 on 2022-01-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
