# Generated by Django 2.2.26 on 2022-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_ftp',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
